var child = [
  { 'dupe': false, 'type': 4, 'name': '403', 'dir': 'c0', 'linked': 1, 'url': 'http://localhost:4200/src/app/403/', 'fetched': true, 'code': 404, 'len': 151, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x8d9ad6a3 },
  { 'dupe': false, 'type': 4, 'name': 'admin', 'dir': 'c1', 'linked': 1, 'url': 'http://localhost:4200/src/app/admin/', 'fetched': true, 'code': 404, 'len': 153, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x536d6b4f },
  { 'dupe': false, 'type': 4, 'name': 'history', 'dir': 'c2', 'linked': 1, 'url': 'http://localhost:4200/src/app/history/', 'fetched': true, 'code': 404, 'len': 155, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xd74c630c },
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c3', 'linked': 1, 'url': 'http://localhost:4200/src/app/login/', 'fetched': true, 'code': 404, 'len': 153, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x193fffeb },
  { 'dupe': true, 'type': 4, 'name': 'model', 'dir': 'c4', 'linked': 1, 'url': 'http://localhost:4200/src/app/model/', 'fetched': true, 'code': 404, 'len': 153, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x5b2d7b08 },
  { 'dupe': false, 'type': 4, 'name': 'services', 'dir': 'c5', 'linked': 1, 'url': 'http://localhost:4200/src/app/services/', 'fetched': true, 'code': 404, 'len': 156, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xc034d68 },
  { 'dupe': false, 'type': 4, 'name': 'transaction', 'dir': 'c6', 'linked': 1, 'url': 'http://localhost:4200/src/app/transaction/', 'fetched': true, 'code': 404, 'len': 159, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x6655f5b2 },
  { 'dupe': true, 'type': 32, 'name': 'app-routing.module.ts', 'dir': 'c7', 'linked': 1, 'url': 'http://localhost:4200/src/app/app-routing.module.ts', 'fetched': true, 'code': 404, 'len': 168, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'app.component.css', 'dir': 'c8', 'linked': 1, 'url': 'http://localhost:4200/src/app/app.component.css', 'fetched': true, 'code': 404, 'len': 164, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
];
