var child = [
  { 'dupe': true, 'type': 4, 'name': '403', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost:4200/src/app/403/', 'fetched': true, 'code': 404, 'len': 151, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce2774a },
  { 'dupe': true, 'type': 4, 'name': 'admin', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost:4200/src/app/admin/', 'fetched': true, 'code': 404, 'len': 153, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce2774a },
  { 'dupe': true, 'type': 4, 'name': 'history', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost:4200/src/app/history/', 'fetched': true, 'code': 404, 'len': 155, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce2774a },
  { 'dupe': true, 'type': 4, 'name': 'login', 'dir': 'c3', 'linked': 2, 'url': 'http://localhost:4200/src/app/login/', 'fetched': true, 'code': 404, 'len': 153, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce2774a },
  { 'dupe': true, 'type': 4, 'name': 'model', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost:4200/src/app/model/', 'fetched': true, 'code': 404, 'len': 153, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce2774a },
  { 'dupe': true, 'type': 4, 'name': 'services', 'dir': 'c5', 'linked': 2, 'url': 'http://localhost:4200/src/app/services/', 'fetched': true, 'code': 404, 'len': 156, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce2774a },
  { 'dupe': true, 'type': 4, 'name': 'transaction', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost:4200/src/app/transaction/', 'fetched': true, 'code': 404, 'len': 159, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce2774a }
];
