var child = [
  { 'dupe': false, 'type': 4, 'name': 'add', 'dir': 'c0', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/add/', 'fetched': true, 'code': 404, 'len': 154, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 3, 0, 0, 0 ], 'sig': 0xf7b8a1f6 },
  { 'dupe': false, 'type': 4, 'name': 'observable', 'dir': 'c1', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/observable/', 'fetched': true, 'code': 404, 'len': 161, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x6aeac68d },
  { 'dupe': false, 'type': 4, 'name': 'operator', 'dir': 'c2', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/operator/', 'fetched': true, 'code': 404, 'len': 159, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x63df8d4f },
  { 'dupe': false, 'type': 4, 'name': 'operators', 'dir': 'c3', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/operators/', 'fetched': true, 'code': 404, 'len': 160, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xc3b1eca0 },
  { 'dupe': false, 'type': 4, 'name': 'scheduler', 'dir': 'c4', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/scheduler/', 'fetched': true, 'code': 404, 'len': 160, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x7bdab918 },
  { 'dupe': false, 'type': 4, 'name': 'symbol', 'dir': 'c5', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/symbol/', 'fetched': true, 'code': 404, 'len': 157, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x5f8ce67 },
  { 'dupe': false, 'type': 4, 'name': 'util', 'dir': 'c6', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/util/', 'fetched': true, 'code': 404, 'len': 155, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xac5628af },
  { 'dupe': true, 'type': 32, 'name': 'BehaviorSubject.js', 'dir': 'c7', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/BehaviorSubject.js', 'fetched': true, 'code': 404, 'len': 168, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'InnerSubscriber.js', 'dir': 'c8', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/InnerSubscriber.js', 'fetched': true, 'code': 404, 'len': 168, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'Notification.js', 'dir': 'c9', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/Notification.js', 'fetched': true, 'code': 404, 'len': 165, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'Observable.js', 'dir': 'c10', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/Observable.js', 'fetched': true, 'code': 404, 'len': 163, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'Observer.js', 'dir': 'c11', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/Observer.js', 'fetched': true, 'code': 404, 'len': 161, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'OuterSubscriber.js', 'dir': 'c12', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/OuterSubscriber.js', 'fetched': true, 'code': 404, 'len': 168, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'Scheduler.js', 'dir': 'c13', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/Scheduler.js', 'fetched': true, 'code': 404, 'len': 162, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'Subject.js', 'dir': 'c14', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/Subject.js', 'fetched': true, 'code': 404, 'len': 160, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'Subscriber.js', 'dir': 'c16', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/Subscriber.js', 'fetched': true, 'code': 404, 'len': 163, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'Subscription.js', 'dir': 'c17', 'linked': 1, 'url': 'http://localhost:4200/rxjs/_esm5/Subscription.js', 'fetched': true, 'code': 404, 'len': 165, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff }
];
