var child = [
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost:8080/login/', 'fetched': true, 'code': 405, 'len': 210, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xf7b8c54b },
  { 'dupe': false, 'type': 4, 'name': 'profile', 'dir': 'c2', 'linked': 1, 'url': 'http://localhost:8080/profile/', 'fetched': true, 'code': 200, 'len': 250, 'decl_mime': 'application/hal+json', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 2, 'issue_cnt': [ 6, 3, 0, 0, 0 ], 'sig': 0x58d9b033 },
  { 'dupe': false, 'type': 4, 'name': 'transfer', 'dir': 'c3', 'linked': 1, 'url': 'http://localhost:8080/transfer/', 'fetched': true, 'code': 405, 'len': 213, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xee8074e6 },
  { 'dupe': true, 'type': 4, 'name': 'transfer', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost:8080/transfer/', 'fetched': true, 'code': 405, 'len': 213, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xf7b8c54b },
  { 'dupe': false, 'type': 8, 'name': 'login', 'dir': 'c6', 'linked': 1, 'url': 'http://localhost:8080/login', 'fetched': true, 'code': 405, 'len': 209, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 3, 0, 0, 0, 0 ], 'sig': 0x5adcce9d },
  { 'dupe': false, 'type': 8, 'name': 'login.sfish', 'dir': 'c7', 'linked': 1, 'url': 'http://localhost:8080/login.sfish', 'fetched': true, 'code': 405, 'len': 215, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 1, 0 ], 'sig': 0xf7b72356 },
  { 'dupe': false, 'type': 8, 'name': 'profile.sfish', 'dir': 'c10', 'linked': 0, 'url': 'http://localhost:8080/profile.sfish', 'fetched': true, 'code': 200, 'len': 250, 'decl_mime': 'application/hal+json', 'sniff_mime': 'application/javascript', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 1, 0 ], 'sig': 0xe733077e }
];
